Added T flip flop
ERC-IIITH/Verilog-Library pull request #4
Opened 2021-10-01 17:54 UTC by swastik1308

The files have been compiled and tested using Icarus Verilog

2021-10-01 22:19 UTC, adithyasunil26 requested changes
@swastik1308 Please read the [contributions guidelines](https://github.com/ERC-IIITH/Verilog-Library/blob/main/CONTRIBUTING.md) carefully. Delete the vcd dump and the compiled file from the PR. You can also remove the terminal screenshot. Also, rename the `tb.v` file to `t_ff_tb.v` as we will be following that convention throughout our project.

2021-10-02 04:48 UTC, swastik1308 commented
Hi @adithyasunil26 . Thanks for the review. I have commited the changes. Please check.

2021-10-02 15:08 UTC, adithyasunil26 requested changes

2021-10-02 15:17 UTC, swastik1308 commented
![verilog_library](https://user-images.githubusercontent.com/64323282/135722540-b2c5ef23-87f8-492e-930b-c1d275c223b0.png)
Works fine now!
@adithyasunil26

2021-10-02 15:24 UTC, adithyasunil26 commented
@swastik1308 This does not seem like the right behaviour for a toggle flip-flop. When T is 0 there should be no change in Q and Qbar and when T is 1, Q should be the complement of its previous state.

2021-10-02 15:38 UTC, swastik1308 commented
![verilog_library](https://user-images.githubusercontent.com/64323282/135723200-0d0cb204-08b0-4bc9-a24b-528c57d8a202.png)
I had messed with the concept. 
@adithyasunil26

2021-10-02 15:42 UTC, adithyasunil26 approved these changes
@swastik1308 This looks good. Will have it merged in soon.

2021-10-02 18:24 UTC, faceless-man1607 approved these changes

2021-10-02 19:09 UTC, merged