Added files for structural and RTL XOR gate implementation
ERC-IIITH/Verilog-Library pull request #8
Opened 2021-10-02 17:38 UTC by KarthikL1729

Added 4 files,  two for structural and RTL modules, and the other two as testbenches for each.

2021-10-02 17:55 UTC, adithyasunil26 requested changes

2021-10-02 17:55 UTC, adithyasunil26 commented on XOR_gate/xor.v
> +module XOR(a, b, o, d);
Keep all the module, file and directory names in small letters.

2021-10-02 17:55 UTC, adithyasunil26 commented on XOR_gate/xor.v
> +        d = 1;
`d` is not required

2021-10-02 17:55 UTC, adithyasunil26 commented on XOR_gate/xor_struct_tb.v
> +        $display("time = %0t, a = %b, b = %b, o = %b", $time, a, b, o);
Substitute this with an `initial` block with `$monitor` command

2021-10-02 17:55 UTC, adithyasunil26 commented on XOR_gate/xor_struct_tb.v
> +module test();
Follow the naming convention for testbench modules mentioned in CONTRIBUTING.

2021-10-02 17:55 UTC, adithyasunil26 commented on XOR_gate/xor_tb.v
> +        $display("time = %0t, a = %b, b = %b, o = %b", $time, a, b, o);
Using the `$monitor` in `initial` block will eliminate the need for this extra wire `d`.

2021-10-03 13:09 UTC, adithyasunil26 requested changes
Looks good to me. Just one change, rename the directory to `xor`. We can get this merged in after that.

2021-10-03 13:17 UTC, adithyasunil26 approved these changes
Good job! Will have this merged in soon.

2021-10-03 13:18 UTC, faceless-man1607 approved these changes

2021-10-03 13:18 UTC, merged